### ISSUE TITLE
[Inspector] different text sizes.

### ISSUE THREAD

**Issue by wdg** [AuroraEditor/AuroraEditor#115]
### Description

[Inspector] different text sizes.

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/1290461/185745277-d104ef08-8679-4f6b-a0c8-901a5c1cee02.png">

### To Reproduce

^

### Expected behavior

Same sizes.

### Version information

Aurora Editor: 1.0 (1)
Commit: d06fb30e72634048395b5dbcdbc756b7f8ecc2f0
MacOS: 13.0 (22A5321d)
Xcode: 14.0 (14A5270f)

**Comment by nanashili** [comment]
You are more than welcome to fix that, because I had no luck
