### ISSUE TITLE
Certain keyboard commands in the text editor move the cursor back one character

### ISSUE THREAD

**Issue by KaiTheRedNinja** [AuroraEditor/AuroraEditor#126]
### Description

When you open an editor and enter a command that doesn't exist (eg. cmd-delete), the cursor moves back one character.

### To Reproduce

1. Open a file
2. Press cmd-delete
3. The cursor moves back one character

### Expected behavior

Whole line deletes

### Version information

Aurora Editor: 1.0
Hash: [e.g. d06fb30e72634048395b5dbcdbc756b7f8ecc2f0]
MacOS: 12.5
Xcode: 14.3

**Comment by wdg** [comment]
Is that default behavior? I did not know that.

But it’s not implemented. (Should be done somewhere in `STTextView`)

**Comment by Ashwonixer** [comment]
Here are the keyboard commands and what they do.

Option + Delete ( Word ) ( I recommend you experiment with this one )
Command + Delete ( whole line )
Shift + Delete ( 1 character )

**Comment by Ashwonixer** [comment]
This issue should be closed
