### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by Angelk90** [AuroraEditor/AuroraEditor#157]
### Description

<img width="590" alt="Schermata 2022-09-02 alle 21 27 14" src="https://user-images.githubusercontent.com/20476002/188223774-ec61c7e2-a68e-477b-8fdd-aa8122e663ff.png">
<img width="591" alt="Schermata 2022-09-02 alle 21 27 23" src="https://user-images.githubusercontent.com/20476002/188223779-5d861275-e176-4c83-82d0-fc1a0abee68e.png">

### To Reproduce

1) open a file
2) open the right side menu

### Version information

Aurora Editor: 1.0 (1)
Commit: 9b046a05a46c4bb308ea87ae9adbeca2b98a1ac3
MacOS: 12.5.1
Xcode: 13.4.1

**Comment by nanashili** [comment]
Fixed in the following PR: [Various UI Fixes](#171)
