### ISSUE TITLE
Hover on commits selected strange effect

### ISSUE THREAD

**Issue by Angelk90** [AuroraEditor/AuroraEditor#158]
### Description

https://user-images.githubusercontent.com/20476002/188224145-dac76280-44b6-4d60-a13d-608f3191aa28.mov

### To Reproduce
1) open a file
2) open the right side menu

### Version information

Aurora Editor: 1.0 (1)
Commit: 9b046a05a46c4bb308ea87ae9adbeca2b98a1ac3
MacOS: 12.5.1
Xcode: 13.4.1

**Comment by nanashili** [comment]
Again, that's a Mac OS issue, nothing we can do about it. As you can see this issue doesn't exist in new versions.

![Screenshot 2022-09-06 at 18 18 35](https://user-images.githubusercontent.com/63672227/188685848-908d110c-f119-4ea3-ab01-3a8efd507a08.png)
