### ISSUE TITLE
Strange effect in the side settings menu

### ISSUE THREAD

**Issue by Angelk90** [AuroraEditor/AuroraEditor#159]
### Description

https://user-images.githubusercontent.com/20476002/188224411-620184cc-fc83-4136-bfa2-1716b2e35736.mov

### To Reproduce
1) open settings

### Version information

Aurora Editor: 1.0 (1)
Commit: 9b046a05a46c4bb308ea87ae9adbeca2b98a1ac3
MacOS: 12.5.1
Xcode: 13.4.1

**Comment by nanashili** [comment]
SwiftUI offers no way to disable this as of now
