### ISSUE TITLE
Modal that does not close

### ISSUE THREAD

**Issue by Angelk90** [AuroraEditor/AuroraEditor#160]
### Description

![image](https://user-images.githubusercontent.com/20476002/188224557-69cdfb7a-1579-41a9-8983-ee7c359d6850.png)

### To Reproduce
1) open Stash Changes

### Version information

Aurora Editor: 1.0 (1)
Commit: 9b046a05a46c4bb308ea87ae9adbeca2b98a1ac3
MacOS: 12.5.1
Xcode: 13.4.1

**Comment by nanashili** [comment]
Fixed in the following PR: [Various UI Fixes](#171)
