### ISSUE TITLE
Modal Github personal access 

### ISSUE THREAD

**Issue by Angelk90** [AuroraEditor/AuroraEditor#162]
### Description

<img width="416" alt="Schermata 2022-09-02 alle 21 37 16" src="https://user-images.githubusercontent.com/20476002/188225026-780409d9-d73b-4a14-8531-35edabb8049b.png">

### Version information

Aurora Editor: 1.0 (1)
Commit: 9b046a05a46c4bb308ea87ae9adbeca2b98a1ac3
MacOS: 12.5.1
Xcode: 13.4.1

**Comment by nanashili** [comment]
Fixed in the following PR: [Various UI Fixes](#171)
