### ISSUE TITLE
Side menu some things to fix

### ISSUE THREAD

**Issue by Angelk90** [AuroraEditor/AuroraEditor#172]
### Description
Differences:
1) Written "Identity and Type" and "Quick Help" different sizes.
2) The size of the select fields look different.
3) Size of the input fields when the left bar widens.

AE:
<img width="719" alt="Schermata 2022-09-06 alle 21 55 52" src="https://user-images.githubusercontent.com/20476002/188726896-75c62966-49cf-4e08-8ef4-e299e6614561.png">

<img width="680" alt="Schermata 2022-09-06 alle 22 01 29" src="https://user-images.githubusercontent.com/20476002/188727818-2e6e0c29-1c8e-4c8b-a00d-76241f3e0a1f.png">

Xcode:
<img width="684" alt="Schermata 2022-09-06 alle 21 56 00" src="https://user-images.githubusercontent.com/20476002/188726901-9e15d35c-99f2-47a1-a31a-f532af98b455.png">
<img width="716" alt="Schermata 2022-09-06 alle 22 01 35" src="https://user-images.githubusercontent.com/20476002/188727825-5aa4f269-47fe-4320-8465-ed3f783d4f28.png">

### Version information
Aurora Editor: 1.0 (1)
Commit: c5f937ee9d7de37de454c7581303658c81f4901f
MacOS: 12.5.1 (21G83)
Xcode: 13.4.1 (13F100)

**Comment by nanashili** [comment]
There's nothing wrong with quick help, and the pickers struggle to resize

**Comment by nanashili** [comment]
Putting this issue as "Not Planned" since there is not a solid fix with Swiftui regarding pickers and them resizing with text is mot consistent.
