### ISSUE TITLE
Strange mouse effect after opening a file

### ISSUE THREAD

**Issue by Angelk90** [AuroraEditor/AuroraEditor#175]
### Description

https://user-images.githubusercontent.com/20476002/188865848-7dd2ce43-76a1-47f5-b7e0-3c4440051ddd.mov

To Reproduce:
1) Hover the mouse over the icons in the side bars
2) Open a file
3) Close the file
4) Hover the mouse over the icons in the side bars

### Version information
Aurora Editor: 1.0 (1)
Commit: d3b9f93ba990dbbe1ed6b911917faea472ae21e6
MacOS: 12.5.1 (21G83)
Xcode: 13.4.1 (13F100)

**Comment by nanashili** [comment]
This issue doesn't seem to exist in MacOS: 13

**Comment by wdg** [comment]
Please check if this issue is still going on.

if we moved to another editor please check again, it should not happen any longer.

(new editor) https://github.com/AuroraEditor/AuroraEditor/pull/234

**Comment by Angelk90** [comment]
@wdg : I tried, at the moment it seems not.

**Comment by nanashili** [comment]
Works fine for me
