### ISSUE TITLE
Being able to open a project via drag and drop in WelcomeView

### ISSUE THREAD

**Issue by nanashili** [AuroraEditor/AuroraEditor#195]

**Comment by japanese-goblinn** [comment]
Hi! Is it issue that I can work on for hacktoberfest?

**Comment by nanashili** [comment]
> Hi! Is it issue that I can work on for hacktoberfest? 

Hi, and welcome. Yes this issue is available for Hacktoberfest.

**Comment by nanashili** [comment]
@ladvoc if you want you can attempt this issue perhaps, tried my luck and was unsuccessful.... We could also extend it if you drop a folder in the editor itself it opens a new AE window with that folder.

**Comment by 0xWDG** [comment]
Uh, i have no idea why this is still open but => #348.
