### ISSUE TITLE
Dragging tabs highlights tab contents

### ISSUE THREAD

**Issue by KaiTheRedNinja** [AuroraEditor/AuroraEditor#226]
### Description

Dragging tabs to rearrange causes the tab content to be selected

### To Reproduce

1. Open a few tabs
2. Drag in the tab area
3. The tab content will be selected

### Expected behavior

Tab content should not be selected

### Version information

Aurora Editor: [e.g. 1.0]
Hash: [e.g. d06fb30e72634048395b5dbcdbc756b7f8ecc2f0]
MacOS: [e.g. 12.3.0]
Xcode: [e.g. 13.3]

**Comment by wdg** [comment]
Does this still happen?

**Comment by KaiTheRedNinja** [comment]
No it doesn’t

**Comment by wdg** [comment]
Closing because the issue seems to be resolved. :D
