### ISSUE TITLE
Inspector width issue

### ISSUE THREAD

**Issue by Angelk90** [AuroraEditor/AuroraEditor#236]
### Description

Every time I open AE, the right side menu opens to me with the following dimensions as shown in the image.

<img width="597" alt="Schermata 2022-09-18 alle 09 18 51" src="https://user-images.githubusercontent.com/20476002/190890504-1a9ce638-8e17-4c68-9068-e504a97ed2d8.png">

### To Reproduce

1. Open any project

### Expected behavior

That every time I open AE, it remembers the previous state of how the menu was.
- Whether it was open or closed
- What size was it if it was open

### Version information

Aurora Editor: 1.0 (1)
Commit: c84b0d052d8cbec8e0375293f1742aac293ce4a9
MacOS: 12.5.1 (21G83)
Xcode: 14.0 (14A309)

**Comment by wdg** [comment]
<img width="1521" alt="image" src="https://user-images.githubusercontent.com/1290461/191345289-e5212897-efdf-4f1e-baa8-4772c2c09d7c.png">

**Comment by 0xWDG** [comment]
This still happens (sometimes)

**Comment by fummicc1** [comment]
I will investigate this issue in my spare time.

**Comment by 0xWDG** [comment]
> I will investigate this issue in my spare time.

Thanks, I've assigned this issue to you, so that we are not working on the same issues.

**Comment by 0xWDG** [comment]
This issue seems to be solved, it does not happen anymore, feel free to re-open if it comes back or create a new issue.
