### ISSUE TITLE
Add More languages for highlighting

### ISSUE THREAD

**Issue by 0xWDG** [AuroraEditor/AuroraEditor#239]
Add More languages for highlighting

- [ ] JavaScript
- [ ] HTML
- [ ] CSS
- [ ] PHP
- [ ] SQL
- [ ] Python
- [ ] Kotlin
- [ ] Java
- [ ] Go
- [ ] Ruby
- [ ] Objective-C
- [ ] C/C++
- [ ] C#
- [ ] Rust
- [ ] Perl
- [ ] R
- [ ] MATLAB

**Comment by artimanputra** [comment]
Hey, I would like to work on this. Can you explain these issue?

**Comment by wdg** [comment]
> Hey, I would like to work on this. Can you explain these issue?

Hey!

Yes, the highlighter works using regular expression, and pre-defined keywords.
There are currently 2 languages implemented (Swift and Haskell)
https://github.com/AuroraEditor/AuroraEditor/blob/main/AuroraEditor/Base/Editor/CodeEditorView/Model/Storage%2BLanguage/LanguageConfiguration.swift

The code editor originates from https://github.com/mchakravarty/CodeEditorView, we ebmedded it because we need to customize it a lot.

i know there is no documentation for the codeeditor since we implemented it this week.
If you have further questions ask them using github issues or our discord-server https://discord.gg/5aecJ4rq9D

**Comment by nanashili** [comment]
Hi @artimanputra, well to give you a summary of what we mean the current editor only supports Haskell and Swift at the moment and we want to add more language support so developers can develop in a multitude of languages.

We currently use tokens/tokenization to achieve the highlighting and will in the future expand this to something like a LSP with token support. The idea is to also detect the kinda of source file the user currently has open by the process of checking the files extension.

For references of how we currently handle highlighting here is some links to the editor:

[LanguageConfiguration.swift](https://github.com/AuroraEditor/AuroraEditor/blob/main/AuroraEditor/Base/Editor/CodeEditorView/Model/Storage%2BLanguage/LanguageConfiguration.swift)
This handles the the syntax of the Haskell and Swift

[CodeStorageDelegate+Tokenisation.swift](https://github.com/AuroraEditor/AuroraEditor/blob/main/AuroraEditor/Base/Editor/CodeEditorView/Model/Storage%2BLanguage/CodeStorageDelegate%2BTokenisation.swift) and [MutableAttributedString.swift](https://github.com/AuroraEditor/AuroraEditor/blob/main/AuroraEditor/Base/Editor/CodeEditorView/Model/Storage%2BLanguage/MutableAttributedString.swift)
This handles the process of converting a sequence of characters into a sequence of lexical tokens (strings with an assigned and thus identified meaning).

**Comment by godrm** [comment]
Hi @0xWDG @nanashili, 
I'm very interesting this project for native editor also. 

I found CodeEditApp used to TreeSitter for highlighter. 
However do you mean that you will make the new code edit from CodeEditorView, right? 
I did try to read the source files you linked, but there's no "Storage Language" sub-folder in Model folder. 
How can I find that folder and files? 

Thanks

**Comment by nanashili** [comment]
> Hi @0xWDG @nanashili, 
> I'm very interesting this project for native editor also. 
> 
> I found CodeEditApp used to TreeSitter for highlighter. 
> However do you mean that you will make the new code edit from CodeEditorView, right? 
> I did try to read the source files you linked, but there's no "Storage Language" sub-folder in Model folder. 
> How can I find that folder and files? 
> 
> Thanks

Hi @godrm we recently moved to a textmate based highlighting as it will allow extension developers to port over VS Code syntaxes and theme which will then be compatible with AE too.

**Comment by godrm** [comment]
> 
> Hi @godrm we recently moved to a textmate based highlighting as it will allow extension developers to port over VS Code syntaxes and theme which will then be compatible with AE too.
> 
> Have a look at the [EditorCore](https://github.com/AuroraEditor/AuroraEditor/tree/main/AuroraEditor%2FBase%2FEditor%2FEditorCore) folder to get an idea of how it works.

Aha! I got it. I found your WIP PR. 
I'll have a look for textmate based highlighting. 

Thanks.
