### ISSUE TITLE
Gutter view flickers and changes width oddly when resizing

### ISSUE THREAD

**Issue by KaiTheRedNinja** [AuroraEditor/AuroraEditor#240]
### Description

The gutter view flickers when resizing. This is due to the `draw` function in the gutter view, and when the view resizes, the layout manager needs a bit of time to arrange things. In the time that the layout manager is laying out views, the gutter view doesn't know what to draw so it just doesn't and returns from the function. Width also changes, which manipulates the starting edge of the code view in odd ways

### To Reproduce

1. Open a tab
2. Resize the window
3. Flickers and resizes in odd ways while dragging

### Expected behavior

No flickering nor resizing

### Version information

Aurora Editor: [e.g. 1.0]
Hash: [e.g. d06fb30e72634048395b5dbcdbc756b7f8ecc2f0]
MacOS: [e.g. 12.3.0]
Xcode: [e.g. 13.3]

**Comment by Maartz** [comment]
I noticed the flickering when resizing.
It's somehow related to the UI so I upload a video of the current behavior.

https://user-images.githubusercontent.com/13407086/209938957-e5cdd03f-504d-4150-80ff-03569d00d972.mov

Got another strange behavior, the gutter just disappear and came back after I extended the window back once again multiple times.

**Comment by 0xWDG** [comment]
We don't use this gutter system anymore, therefore i close this issue. if you keep encountering it, then please add a comment and we'll reopen the issue.
