### ISSUE TITLE
Minimap flickers when resizing

### ISSUE THREAD

**Issue by KaiTheRedNinja** [AuroraEditor/AuroraEditor#241]
### Description

The minimap flickers with certain parts turning black while resizing, first reported by AngelK.

Appears to be Monterey only, as wdg and Nanashili are unable to reproduce it on Ventura.

### To Reproduce

1. Open a file about twice as long as the minimap shows
2. Scroll to near the bottom
3. Resize the window
4. The minimap will flicker

### Expected behavior

No minimap flickering

### Version information

Aurora Editor: [e.g. 1.0]
Hash: [e.g. d06fb30e72634048395b5dbcdbc756b7f8ecc2f0]
MacOS: [e.g. 12.3.0]
Xcode: [e.g. 13.3]

**Comment by 0xWDG** [comment]
Closing as it is not present on Ventura.
