### ISSUE TITLE
Linenumbers are not correct if >999

### ISSUE THREAD

**Issue by wdg** [AuroraEditor/AuroraEditor#242]
![image](https://user-images.githubusercontent.com/1290461/191003146-aad0248b-424e-4927-be15-216185f84f0a.png)

**Comment by Angelk90** [comment]
@wdg : A strange thing happens with last number:
<img width="122" alt="Schermata 2022-09-20 alle 19 54 41" src="https://user-images.githubusercontent.com/20476002/191329795-0865f6f5-9330-4f64-99f8-7ef721ee6c6c.png">
