### ISSUE TITLE
Re-opening aurora editor does not show editor.

### ISSUE THREAD

**Issue by Angelk90** [AuroraEditor/AuroraEditor#250]
### Description
Re-opening aurora editor does not show editor.

https://user-images.githubusercontent.com/20476002/191467890-efcd6a25-06bb-4bd5-99e3-8fed1bf27712.mov

### To Reproduce

1) open a project
2) open a file
3) close the program
4) open the same project

### Expected behavior

That the file opened in the tab you see the code.

### Version information

Aurora Editor: 1.0 (1)
Commit: 769ad8ed05a33308b514df7c312c882537f1b48e
MacOS: 12.5.1 (21G83)
Xcode: 14.0 (14A309)

**Comment by nanashili** [comment]
It's not an issue if it hasn't been implemented yet

**Comment by KaiTheRedNinja** [comment]
Not just from the menu bar. It appears that opening any project that was closed with a tab causes that bugged out tab to exist
