### ISSUE TITLE
Human-readable version of Software License

### ISSUE THREAD

**Issue by sbutler-gh** [AuroraEditor/AuroraEditor#255]
### Is your feature request related to a problem? Please describe.

I don't understand the IP License clause

### Describe the solution you'd like

A simple and concise explanation of the softawre license, including the IP License clause.

For example, what does the IP License mean in practice?  How does it affect the MIT License?

I undersetand what it means for the AuroraEdit Logo — if somebody forks the project, they can't use the AuroraEdit logo.  That makes sense.

I don't understand what it means for the rest of the files in the IP License clause.

### Describe alternatives you've considered

Not sure if there's a need to describe alternatives when the request is better documentation, but in any case, the only alternatives seem to be:

* Changing the software license to something more standard (and thereby eliminating friction of people joining/contributing to the project, due to unfamiliarity with the license)
* Keeping the license and documentation as is (which would result in more confused people like myself)

### Additional context

N/A

**Comment by wdg** [comment]
Hi,

Thanks for reporting, we will discuss this issue and we will come asap with feedback/an solution

**Comment by nanashili** [comment]
@sbutler-gh, Thank you for bringing this up. We will have a fix for this in the next few minutes.

**Comment by nanashili** [comment]
@sbutler-gh It should be more understandable now.
