### ISSUE TITLE
Implement extension functions

### ISSUE THREAD

**Issue by 0xWDG** [AuroraEditor/AuroraEditor#284]
Implement extension functions.
\* Please note, that this list can change, and maybe not all functions listed below will be implemented.

**AE To Extensions**
- [x] func didOpen(workspace: String, file: String, contents: Data)
- [x] func didOpen(file: String, contents: Data)
- [x] func didSave(file: String)
- [x] func didMoveCaret(row: Int, column: Int)
- [x] func didActivateTab(file: String)
- [x] func didDeactivateTab(file: String)
- [x] func didToggleNavigatorPane(opened: Bool)
- [x] func didToggleInspectorPane(opened: Bool)

**Extensions To AE**
- [x] func showNotification(message: String)
- [x] func showWarning(message: String)
- [x] func showError(message: String)
- [x] func openSettings()

**Comment by 0xWDG** [comment]
See https://github.com/AuroraEditor/AEExtensionKit-Documentation for documentation, and usage examples

**Comment by nanashili** [comment]
'showError', 'showInformantion' and 'showWarning' should rather be used to send notifications to the editor instead.

**Comment by 0xWDG** [comment]
> 'showError', 'showInformantion' and 'showWarning' should rather be used to send notifications to the editor instead.

To the toolbar?
