### ISSUE TITLE
Menu problem

### ISSUE THREAD

**Issue by Angelk90** [AuroraEditor/AuroraEditor#290]
### Description

<img width="426" alt="Schermata 2022-10-11 alle 23 34 27" src="https://user-images.githubusercontent.com/20476002/195202729-76c5b4dd-0e07-4e39-b525-f1344c86d0cd.png">

### Version information

Aurora Editor: 1.0 (1)
Commit: f18b3cd1f118d1986d228f0f41077864165c66d3
MacOS: 12.5.1 (21G83)
Xcode: 14.0.1 (14A400)

**Comment by 0xWDG** [comment]
What is exactly the problem? it's unclear to mee.

**Comment by KaiTheRedNinja** [comment]
Its wide

**Comment by KaiTheRedNinja** [comment]
This is a Monterey issue, solved in ventura. @nanashili  knows how to fix this.

**Comment by 0xWDG** [comment]
solved in ventura
