### ISSUE TITLE
Add contributors

### ISSUE THREAD

**Issue by 0xWDG** [AuroraEditor/AuroraEditor#293]

**Comment by 0xWDG** [comment]
@allcontributors please add @Blackhole1123 for bugs

**Comment by 0xWDG** [comment]
@allcontributors please add @code-reaper08 for bugs

**Comment by nanashili** [comment]
@allcontributers please add @Lakwinder for bugs

**Comment by nanashili** [comment]
@allcontributors please add @lakwinderr for bugs

**Comment by nanashili** [comment]
@allcontributors please add @Lakhwinderr for bugs

**Comment by 0xWDG** [comment]
@allcontributors please add @briangor for design
