### ISSUE TITLE
Minimap not visible

### ISSUE THREAD

**Issue by 0xWDG** [AuroraEditor/AuroraEditor#302]
### Description

<img width="1223" alt="image" src="https://user-images.githubusercontent.com/1290461/196496274-0b230f54-236c-4953-8e66-756d1fd4ec36.png">

after resizing an mini minimap becomes visible
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/1290461/196496546-b7ba6d9b-2bc2-44a9-8cd7-6349635fb022.png">

### To Reproduce

Opening on a 13" Mac

### Expected behavior

Always show minimap

### Version information

Aurora Editor: 1.0 (1)
Commit: 278483cf0b62d96db1229a66d449fc6ea88ed7f5
MacOS: 13.0 (22A5358e)
Xcode: 14.0.1 (14A400)

**Comment by KaiTheRedNinja** [comment]
I think a while back nanashili did something with the minimap to allow it to automatically hide/show, may have introduced this bug.

**Comment by 0xWDG** [comment]
Closing this, since this is the old editor.
