### ISSUE TITLE
Switching from extension explore to extension installed crashes Aurora

### ISSUE THREAD

**Issue by TheGlorySaint** [AuroraEditor/AuroraEditor#315]
### Description

I newly downloaded Aurora and wanted to check the available extensions. I show 1 available extension(On your Website it shows more) and when switching from the explore tab to the installed tab, Aurora crashes/closes without the Crash Window that comes from macOS.

### To Reproduce

Open Aurora
Switch to extension Tab (explore should be "active")(Not the Menu where also Preferences is found)
Switch in the extension Tab to installed
Now Aurora closes for me.

### Expected behavior

Aurora should stay active and displays the installed extensions

### Version information

Aurora Editor: 1.0①
Commit: a66d72d7291812b6259f22b7df524bf9baf1f0c5
MacOS: Ventura 13.0 
Xcode: 14.1

**Comment by 0xWDG** [comment]
AFAIK You can't install extensions from the store yet, there is no code to make this happen.
It should not crash.
i add Enhancement as well.

**Comment by 0xWDG** [comment]
Crash confirmed.

**Comment by 0xWDG** [comment]
The problem occurs here: https://github.com/AuroraEditor/AuroraEditor/blob/c399cd19152ad3d35c9aba6141b97e3643c59c99/AuroraEditor/Base/NavigatorSidebar/UI/ExtensionNavigator/Explore/ExploreExtensionsView.swift#L34-L35

If this line is disabled the crash does not happen, it only happens at unload.
Changing `Plugin` to an Hashed struct did not solve this crash.
a check using `if .isEmpty` did neither.

```
2022-11-18 14:39:02.842726+0100 AuroraEditor[95925:2225933] [General] Row index 0 out of row range (numberOfRows: 0) for <SwiftUI.ListCoreOutlineView: 0x146a67e00>
```

cc: @nanashili
