### ISSUE TITLE
Can't download Aurora Update

### ISSUE THREAD

**Issue by TheGlorySaint** [AuroraEditor/AuroraEditor#316]
### Description

Newly installed Aurora from the GitHub Nightly Build Link. Opened Preferences, switched to Update and a new update is displayed. Then I click on Update Now, but nothing is happening. Change no setting, just the fresh install. 

<img width="592" alt="Bildschirm­foto 2022-11-08 um 09 42 13" src="https://user-images.githubusercontent.com/21318321/200516669-da19d410-254b-46d8-82b5-8aca28c1fd95.png">

### To Reproduce

Install Aurora
Open Prefrences
Switch to Update
And Update should be displayed
Click on Update now
now, nothing is happening

### Expected behavior

The Update should download and install

### Version information

Aurora Editor: 1.0①
Commit: a66d72d7291812b6259f22b7df524bf9baf1f0c5
MacOS: Ventura 13.0
Xcode: 14.1

**Comment by nanashili** [comment]
I still meed to find a way to validate the hash and install patches instead of the whole program over.
