### ISSUE TITLE
Settings tabs truncation

### ISSUE THREAD

**Issue by Maartz** [AuroraEditor/AuroraEditor#344]
### Description

The settings have a list of tabs.
It seems that the name of some tabs are truncated.
But as long as you move the separating line, the words doesn't take the full space and are still truncated.

Opening:

<img width="762" alt="image" src="https://user-images.githubusercontent.com/13407086/209722859-0a36d6bb-4c98-4aa9-8ba8-87c8af5e3763.png">

After pulling the separator:

<img width="762" alt="image" src="https://user-images.githubusercontent.com/13407086/209722930-6130d09f-c444-4a4a-8a12-e4998284eddc.png">

### To Reproduce

1. Open up Aurora Editor.
2. Cmd + , or AuroraEditor > Settings

### Expected behavior

The expected behavior is that the text expands to the full space available.

### Version information

Aurora Editor: 1.0
Commit: 81d84367
MacOS: 13.2 (a) 
Xcode: 14.2 (14C18)

**Comment by 0xWDG** [comment]
Fixed in https://github.com/AuroraEditor/AuroraEditor/pull/345
