### ISSUE TITLE
Nightly Build Artifact is over 90 Days old

### ISSUE THREAD

**Issue by nshardy** [AuroraEditor/AuroraEditor#429]
Hi there everyone,

I had no idea where to put this information but the Nightly Build download link isn't working because the artefact is over 90 days old. I'm really hoping I'm not bringing up an issue people already know about, but I had looked through the Issues and the Discussions tab to see if this had been brought up before and it hasn't.

**Comment by 0xWDG** [comment]
Hey,

I'm aware of this issue, i need to upload new certificates.
I'm on holiday right now and have no laptop available, also i need to check how i can make and upload the new certificates.

**Comment by nshardy** [comment]
@0xWDG Thank you for the quick reply, enjoy your holiday!

**Comment by 0xWDG** [comment]
#430 did fail (failed on timeout of 30 minutes)
#431 is running now (and will hopefully work)

**Comment by 0xWDG** [comment]
Its live: https://nightly.link/AuroraEditor/AuroraEditor/workflows/nightly/development/AuroraEditor_Nightly.zip
