### ISSUE TITLE
Appearance Selector displaying non interpreted data

### ISSUE THREAD

**Issue by Maartz** [AuroraEditor/AuroraEditor#435]
### Description

The text is truncated and thus, Dark is not displayed correctly.

![CleanShot 2023-09-02 at 21 31 04@2x](https://github.com/AuroraEditor/AuroraEditor/assets/13407086/88a6d15d-298a-4ee5-ae80-0e7704ead911)

### To Reproduce

1. Go to "Preferences"
2. General
3. Appearance
4. Appearance selector
5. Check the UI

### Expected behavior

Dark should be displayed.

### Version information

Aurora Editor: 1.0 (1)
Commit: 64508702a686f1c7137d96ef713e1483905bf0c3
MacOS: Sonoma latest beta for dev
Xcode: 15.0 beta 8 (15A5229m)

**Comment by 0xWDG** [comment]
Fixed in #436
