### ISSUE TITLE
Artefact on welcome window

### ISSUE THREAD

**Issue by Maartz** [AuroraEditor/AuroraEditor#441]
### Description

There's this strange artefact, seems to be a cursor/selector thing.

![CleanShot 2023-09-03 at 11 46 34@2x](https://github.com/AuroraEditor/AuroraEditor/assets/13407086/bf96a0e1-69e1-41cd-bea3-0c91647a29af)

### To Reproduce

Just open Aurora Editor

### Expected behavior

To have a clean UI w/o a blue rectanlge.

### Version information

Aurora Editor: Aurora Editor: 1.0 (1)
Commit: 7f7b465a3945af5717ef6d9faee57647ac8de79a
MacOS: 14.0 (23A5337a)
Xcode: 15.0 (15A5229m)

**Comment by 0xWDG** [comment]
I'm unable to reproduce this.

**Comment by Maartz** [comment]
It appears when the focus is on the window, otherwise, no artifact.
This is why I think it's linked to the cursor, with smth like a hidden field.

![CleanShot 2023-09-03 at 14 01 25](https://github.com/AuroraEditor/AuroraEditor/assets/13407086/5176a6a3-278e-45d5-b203-13e6360a1266)

**Comment by 0xWDG** [comment]
The problem is `KeyViewProxy`

<img width="1552" alt="image" src="https://github.com/AuroraEditor/AuroraEditor/assets/1290461/c644851d-5905-4ae9-9d18-bd24abc34e9e">
