### ISSUE TITLE
Aurora crashes when loading a file - Unwrap of optional

### ISSUE THREAD

**Issue by Maartz** [AuroraEditor/AuroraEditor#442]
### Description

I've opened a document in AE.
The issue comes from the preferences.

```swift
    @State
    private var font: NSFont = {
        let size = AppPreferencesModel.shared.preferences.textEditing.font.size
        let name = AppPreferencesModel.shared.preferences.textEditing.font.name // textEditing seems to be the culprit.
        return NSFont(name: name, size: Double(size)) ?? NSFont.monospacedSystemFont(ofSize: 12, weight: .regular)
    }()
```

```
[2023-09-03 11:55:09.363] ThemeModel.swift:80 ERROR: [Error Domain=NSCocoaErrorDomain Code=516 "Impossible to copy from « auroraeditor-xcode-dark.json » to « Themes » : an element is already named like that." UserInfo={NSSourceFilePathErrorKey=/Users/maartz/Library/Developer/Xcode/DerivedData/Aurora_Editor-bjhtacwfrhlbuigekioqefxynzim/Build/Products/Debug/Aurora Editor.app/Contents/Resources/auroraeditor-xcode-dark.json, NSUserStringVariant=(
    Copy
), NSDestinationFilePath=/Users/maartz/Library/Application Support/com.auroraeditor/Themes/auroraeditor-xcode-dark.json, NSFilePath=/Users/maartz/Library/Developer/Xcode/DerivedData/Aurora_Editor-bjhtacwfrhlbuigekioqefxynzim/Build/Products/Debug/Aurora Editor.app/Contents/Resources/auroraeditor-xcode-dark.json, NSUnderlyingError=0x6000031dbbd0 {Error Domain=NSPOSIXErrorDomain Code=17 "File exists"}}]

AuroraEditor/CodeEditorViewWrapper.swift:36: Fatal error: Unexpectedly found nil while unwrapping an Optional value
```

### To Reproduce

1. Open Aurora
2. Open a file (here it was .ex file but I do not think it's related)

### Expected behavior

Do not unwrap an optional and get nil without nil coalescing. 

### Version information

Aurora Editor: Aurora Editor: 1.0 (1)
Commit: 7f7b465a3945af5717ef6d9faee57647ac8de79a
MacOS: 14.0 (23A5337a)
Xcode: 15.0 (15A5229m)

### Additional context

I do not know if this comes from cached data or something like that.
Now I'm unable to compile AE again.

**Comment by Maartz** [comment]
So this is defo linked to derived data.
But does a prod build release on these as well?

**Comment by 0xWDG** [comment]
It has to do with `AuroraEditor/CodeEditorViewWrapper.swift:36: Fatal error: Unexpectedly found nil while unwrapping an Optional value` crashing while force unwrapping.
The underlying error should be fixed but it shouldn't crash because of this error.

**Comment by Maartz** [comment]
Yes, I've checked for this.
But to be able to build again I've cleaned DD and was able to build again.
If it can give any clues, I prefer to mention it.
