### ISSUE TITLE
Automatically update build version

### ISSUE THREAD

**Issue by 0xWDG** [AuroraEditor/AuroraEditor#464]
### Is your feature request related to a problem? Please describe.

Automatically update build version

### Describe the solution you'd like

Run something like:

```bash
agvtool new-version -all `date -u "+%Y%m%d.%H%M"`
```

on build

### Describe alternatives you've considered

Updating it by hand.

### Additional context

None

**Comment by nanashili** [comment]
Where so we want this to happen? As a GitHub action or in the editor itself?

**Comment by 0xWDG** [comment]
> Where so we want this to happen? As a GitHub action or in the editor itself?

Preferably on GitHub, so we don't need to re sync across all forks.

**Comment by nanashili** [comment]
Maybe in the build script?
