### ISSUE TITLE
Color palette strange behavior

### ISSUE THREAD

**Issue by Angelk90** [AuroraEditor/AuroraEditor#479]
### Description

The Color Palette has a strange behavior, when I move the slider to change color, it becomes darker.

https://github.com/AuroraEditor/AuroraEditor/assets/20476002/32f860f2-bcba-48d4-b4f2-01f4f051b72d

### To Reproduce

Tested on Themes -> Terminal -> Cursor

### Version information

Aurora Editor: 1.0 (20230915.2006)
Commit: 38620af465c62bd496aa333090247146b1107fa4
MacOS: 13.5.2 (22G91)
Xcode: 14.3.1 (14E300c)

**Comment by 0xWDG** [comment]
I cannot recreate this problem, also the color picker is a MacOS system thing which we have not a lot of influence on.
It is behaving a little bit laggy but not so extreme as in your screen recording.
I close this for now, if the problem occurs again, please feel free to reopen or make a new issue.
