### ISSUE TITLE
Clipped text of terminal color attributes

### ISSUE THREAD

**Issue by Angelk90** [AuroraEditor/AuroraEditor#480]
### Description

As you can see from the images the texts are cut.

<img width="1440" alt="Screenshot 2023-09-16 alle 12 05 10" src="https://github.com/AuroraEditor/AuroraEditor/assets/20476002/7ba8f631-282e-4cc4-a663-6eb71eeac281">

### To Reproduce

Tested on Themes -> Terminal

### Version information

Aurora Editor: 1.0 (20230915.2006)
Commit: 38620af465c62bd496aa333090247146b1107fa4
MacOS: 13.5.2 (22G91)
Xcode: 14.3.1 (14E300c)

**Comment by mishapark** [comment]
Hi, please assign this issue to me
