### ISSUE TITLE
Preview of non-aligned themes

### ISSUE THREAD

**Issue by Angelk90** [AuroraEditor/AuroraEditor#481]
### Description

<img width="307" alt="Screenshot 2023-09-16 alle 12 30 47" src="https://github.com/AuroraEditor/AuroraEditor/assets/20476002/24a725ca-6a9b-4862-9aba-3004f5c6ac5a">

### To Reproduce

Tested on Themes

### Version information

Aurora Editor: 1.0 (20230915.2006)
Commit: 38620af465c62bd496aa333090247146b1107fa4
MacOS: 13.5.2 (22G91)
Xcode: 14.3.1 (14E300c)

**Comment by mishapark** [comment]
@0xWDG I already created a PR, but please assign this issue to me :)
