### ISSUE TITLE
Terminal cursor ability to set transparency

### ISSUE THREAD

**Issue by Angelk90** [AuroraEditor/AuroraEditor#482]
### Description

As you can see from the default image on the terminal where the cursor is, you cannot see the letter underneath, even if you change the color.

It would be useful to be able to set transparency.

<img width="263" alt="Screenshot 2023-09-16 alle 12 34 32" src="https://github.com/AuroraEditor/AuroraEditor/assets/20476002/1f4f4920-f4a3-43d7-b332-f9fffd27a3e3">

### Version information

Aurora Editor: 1.0 (20230915.2006)
Commit: 38620af465c62bd496aa333090247146b1107fa4
MacOS: 13.5.2 (22G91)
Xcode: 14.3.1 (14E300c)

**Comment by czuria1** [comment]
Hello, mind if I work on this issue?

**Comment by 0xWDG** [comment]
> Hello, mind if I work on this issue?

Thanks for working on this issue, I assigned this to you.

**Comment by nanashili** [comment]
Hi, you are more than welcome. I just have the idea that you might have to clone the terminal package.
