### ISSUE TITLE
Localisation missing (Settings -> Accounts)

### ISSUE THREAD

**Issue by 0xWDG** [AuroraEditor/AuroraEditor#502]
### Description

<img width="872" alt="image" src="https://github.com/AuroraEditor/AuroraEditor/assets/1290461/c8c6feb9-fa02-4be4-9394-edb034021bc4">

### To Reproduce

Settings -> Accounts

### Expected behavior

See localized text

### Version information

Aurora Editor: 1.0 (1)
Commit: 3e146109b7d2128ce2a5c4b1e5f54bdfa5e2da22
MacOS: 14.0 (23A339)
Xcode: 15.0 (15A240d)

**Comment by ameen4455** [comment]
Hi!
Could I work on this issue?

**Comment by nanashili** [comment]
> Hi!
> 
> Could I work on this issue?

@ameen4455 Hi, yes you can.
