### ISSUE TITLE
Open in integrated terminal

### ISSUE THREAD

**Issue by Angelk90** [AuroraEditor/AuroraEditor#524]
### Is your feature request related to a problem? Please describe.

Being able to open a terminal with the relative path more easily.

### Describe the solution you'd like

Like vscode does, it would be nice to have this feature.

<img width="283" alt="Screenshot 2023-09-23 alle 15 17 51" src="https://github.com/AuroraEditor/AuroraEditor/assets/20476002/275af14e-c60d-4c51-98bd-fe26cc0ec735">

**Comment by 0xWDG** [comment]
Some notes:

Open terminal in a specific path `/usr/bin/open -b com.apple.terminal "/directory/path"`
Terminal feed to change folder `\u{1b}]7;file:///localhost/directory/path\u{7}`
SwiftTerm: `hostCurrentDirectoryUpdate(source: TerminalView, directory: String?)`
