### ISSUE TITLE
The Application screenshot on the README is actually CodeEdit?

### ISSUE THREAD

**Issue by nshardy** [AuroraEditor/AuroraEditor#558]
So I noticed this a while ago, and I thought somebody may have brought it up before but apparently I was wrong. Please correct me if I'm wrong, but the screenshot for Aurora Editor is actually a screenshot from CodeEdit, and the screenshot for CodeEdit is the screenshot from Aurora Editor.

On the left is the GitHub for Aurora Editor with Aurora Editor application, and on the right is the GitHub for CodeEdit with the CodeEdit application.

<img width="1680" alt="Screenshot 2023-10-20 at 6 21 26 PM" src="https://github.com/AuroraEditor/AuroraEditor/assets/104463569/c540bd3d-aad7-4577-af6b-86b2492e67b7">

**Comment by bombardier200** [comment]
The one for CodeEdit is actually a Figma made by Austin for CodeEdit, it's not an actual screenshot of CodeEdit.

**Comment by 0xWDG** [comment]
Both are mockups indeed.
AFAIK they are bot (based on) the same fig a made by Austin.
