### ISSUE TITLE
Crash on close of tabs

### ISSUE THREAD

**Issue by nanashili** [AuroraEditor/AuroraEditor#58]
Saving has been fixed and no issue has come where it causes a problem except when closing tabs for some reason it crashes when saving from close, which is weird. But the best part is the there is no Id attached to the item so how does it close in the first place?!
![Screenshot_2022-08-06_at_10 52 35](https://user-images.githubusercontent.com/63672227/183242390-3c0a2ca2-3d0e-4f1f-9593-28dd1e84cc71.png)

And why the *#$@ is it opening multiple times. What kinda logic is this I'm very confused by this.

**Comment by wdg** [comment]
Does this still happen?

**Comment by nanashili** [comment]
Seems like issue is fixed, closing this issue until further notice
