### ISSUE TITLE
Embed Editor in a MacOS App

### ISSUE THREAD

**Issue by ayrtonsoftware** [AuroraEditor/AuroraEditor#580]
### Describe the solution you'd like

I need a code editor not standalone app.

### Describe alternatives you've considered

Tried [mchakravarty/CodeEditorView](https://github.com/mchakravarty/CodeEditorView) - got too many unexplained compile errors

### Additional context

No other context

**Comment by 0xWDG** [comment]
Hey,

I don't see this as an Aurora editor problem, you have raised an issue on that repo.
If you want specific information about how to initialize, look at the playground in that repo, and if you want to see a more advanced init you can browse to AE's, please note that ours is heavily modified and can give unexpected results.
I would suggest to init without the custom parameters.

```swift
import SwiftUI
import CodeEditorView


struct Editor: View {
  @State private var text = "main = print 42"

  var body: some View {
    CodeEditor(text: $text)
  }
}
```
