### ISSUE TITLE
Nightly Build Requires macOS 13.0 Despite Documentation Specifying 12.0

### ISSUE THREAD

**Issue by RyloRiz** [AuroraEditor/AuroraEditor#597]
### Description

In the release notes and in the wiki, it is stated that the minimum requirement is macOS 12.0, a.k.a. Monterey, to run AuroraEditor, but upon running the app, an error is presented saying the minimum system requirement is 13.0. **Either the minimum requirement was incorrectly set, or the docs have not been updated.**

### To Reproduce

1. Download the latest nightly release.
2. Attempt to install on macOS Monterey (12.0).

### Expected behavior

I should be able to run AuroraEditor on macOS Monterey (12.0).

### Version information

Aurora Editor: [e.g. 1.0]
Commit: [e.g. d06fb30e72634048395b5dbcdbc756b7f8ecc2f0]
MacOS: [e.g. 12.3.0]
Xcode: [e.g. 13.3]

**Comment by 0xWDG** [comment]
We need to investigate where this went wrong, maybe we are still able to revert this to 12. Hopefully it doesn't break to much.

**Comment by 0xWDG** [comment]
@aurora-editor-bot please assign me

**Comment by 0xWDG** [comment]
Hey @RyloRiz,

The nightly - beta - stable builds are running now, if building/notarizing does not fail in about 30 minutes there will be a new version for MacOS 12.0 and up.

Thanks for creating the issue.

**Comment by 0xWDG** [comment]
@RyloRiz All builds are updated.
