### ISSUE TITLE
Buttons in navigator should not be focusable

### ISSUE THREAD

**Issue by 0xWDG** [AuroraEditor/AuroraEditor#609]
### Description

Buttons in the navigator should not be focusable

<img width="1110" alt="B26D2C34-C4D6-46F8-8504-DD8FDCBF313B" src="https://github.com/AuroraEditor/AuroraEditor/assets/1290461/16e42804-0fdf-4ceb-8170-640f10a6bfac">

### To Reproduce

Open the editor

### Expected behavior

Do not show focus.

### Version information

Aurora Editor: 1.0 (1)
Commit: 02ce35297004a96c9b9c769eda55b4fc2a8a1ca6
MacOS: 14.1 (23B74)
Xcode: 15.0.1 (15A507)

**Comment by aurora-care-bear** [comment]
Thanks for submitting a issue!
to assign this issue to yourself please comment `@aurora-care-bear please assign me`
