### ISSUE TITLE
Crash when opening folder

### ISSUE THREAD

**Issue by JiangYanlong** [AuroraEditor/AuroraEditor#627]
### Description

When opening the folder, the software will crash. What Mac version is supported? My computer is Ventura 13.4.1 (c) (22F770820d)

### To Reproduce

none

### Expected behavior

none

### Version information

none

### Additional context

none

**Comment by aurora-care-bear** [comment]
Thanks for submitting a issue!
to assign this issue to yourself please comment `@aurora-care-bear please assign me`

**Comment by JiangYanlong** [comment]
@aurora-care-bear

**Comment by 0xWDG** [comment]
Hey @JiangYanlong MacOS 13 should be supported.

can you please provide some more information about the folder which you are loading.

1. Is it an iCloud enabled folder?
2. (If on iCloud) are the files downloaded or on the cloud (see the cloud icon or cloud with down arrow icon)
3. How many files are in the folder 
4. How many directories are in the folder
5. Can you see a reason/crash in Xcode?
6. did you use a pre-compiled binary?

**Comment by 0xWDG** [comment]
Due to inactivity we close this issue.
