### ISSUE TITLE
`ExtensionWKWebView` does not utilise baseURL.

### ISSUE THREAD

**Issue by 0xWDG** [AuroraEditor/AuroraEditor#642]
### Description

`ExtensionWKWebView` does not utilise baseURL.

### To Reproduce

N/A

### Expected behavior

set baseURL

### Version information

N/A

**Comment by aurora-care-bear** [comment]
Thanks for submitting a issue!
to assign this issue to yourself please comment `@aurora-care-bear please assign me`

**Comment by 0xWDG** [comment]
@aurora-care-bear please assign me
