### ISSUE TITLE
Closing an extension opened window crashes the JavaScript-extension interface

### ISSUE THREAD

**Issue by 0xWDG** [AuroraEditor/AuroraEditor#651]
### Description

Closing an extension opened window crashes the JavaScript-extension interface

### To Reproduce

Close an extension window which is opened as tab

### Expected behavior

Close and not crash 

### Version information

All JS extension enabled versions are impacted.

**Comment by aurora-care-bear** [comment]
Thanks for submitting a issue!
to assign this issue to yourself please comment `@aurora-care-bear please assign me`

**Comment by 0xWDG** [comment]
The impacted line.

https://github.com/AuroraEditor/AuroraEditor/blob/development/AuroraEditor/Base/Extensions/Models/JSSupport.swift#L159
