### ISSUE TITLE
Text is rendered white on a white background

### ISSUE THREAD

**Issue by 0xWDG** [AuroraEditor/AuroraEditor#657]
### Description

Sometimes the text will be rendered white on a white background,
after changing the theme the rendering is okay.

![WhatsApp Image 2024-05-22 at 15 37 30](https://github.com/AuroraEditor/AuroraEditor/assets/1290461/d55f38f7-5608-43a7-8851-e904e085be32)

### To Reproduce

Sometimes the text will be rendered white on a white background,
after changing the theme the rendering is okay.

This is on single file mode, i have no idea how it behaves elsewhere.

### Expected behavior

Highlighting or black text

### Version information

Commit 9a7364ae59f4234602755cc11e2e5cfa84d3c791

### Additional context

This is a bug which got reported to me by someone else, therefore i made this issue to track it.

**Comment by aurora-care-bear** [comment]
Thanks for submitting a issue!
to assign this issue to yourself please comment `@aurora-care-bear please assign me`

**Comment by 0xWDG** [comment]
Fixed in https://github.com/AuroraEditor/AuroraEditor/pull/745
