### ISSUE TITLE
Show issues in inspector panel

### ISSUE THREAD

**Issue by 0xWDG** [AuroraEditor/AuroraEditor#659]
### Is your feature request related to a problem? Please describe.

Nope.

### Describe the solution you'd like

Show issues in inspector panel (maybe trough an extension?)

### Describe alternatives you've considered

None

### Additional context

Maybe it is a nice feature to have

**Comment by aurora-care-bear** [comment]
Thanks for submitting a issue!
to assign this issue to yourself please comment `@aurora-care-bear please assign me`

**Comment by 0xWDG** [comment]
I have no idea anymore, closing this.
