### ISSUE TITLE
Crash on (fast) switching tab

### ISSUE THREAD

**Issue by 0xWDG** [AuroraEditor/AuroraEditor#662]
### Description

<img width="1552" alt="image" src="https://github.com/AuroraEditor/AuroraEditor/assets/1290461/efb87690-f2af-4db6-adc6-468938ae005a">

https://github.com/AuroraEditor/AuroraEditor-TextView/blob/main/Sources/AuroraEditorTextView/Model/TreeSitter/TreeSitterClient.swift#L232

### To Reproduce

Switching between JSON files

### Expected behavior

No Crash

### Version information

https://github.com/AuroraEditor/AuroraEditor/pull/660

**Comment by aurora-care-bear** [comment]
Thanks for submitting a issue!
to assign this issue to yourself please comment `@aurora-care-bear please assign me`

**Comment by 0xWDG** [comment]
Deprectated, this code is replaced.
