### ISSUE TITLE
Thread 1: EXC_BAD_ACCESS (code=1, address=0x100000000)

### ISSUE THREAD

**Issue by 0xWDG** [AuroraEditor/AuroraEditor#663]
### Description

<img width="1552" alt="image" src="https://github.com/AuroraEditor/AuroraEditor/assets/1290461/0ef2d71b-74b6-4fe5-84fb-73d1fad1ddcb">

https://github.com/AuroraEditor/AuroraEditor-TextView/blob/main/Sources/AuroraEditorTextView/Controller/TextViewController%2BTextFormation.swift#L73

### To Reproduce

Switch tabs (fast)

### Expected behavior

No crash

### Version information

Latest.

**Comment by aurora-care-bear** [comment]
Thanks for submitting a issue!
to assign this issue to yourself please comment `@aurora-care-bear please assign me`

**Comment by 0xWDG** [comment]
Deprectated, this code is replaced.
