### ISSUE TITLE
Thread 9: EXC_BAD_ACCESS (code=1, address=0x48)

### ISSUE THREAD

**Issue by 0xWDG** [AuroraEditor/AuroraEditor#664]
### Description

Opening JSON

<img width="1512" alt="image" src="https://github.com/AuroraEditor/AuroraEditor/assets/1290461/92e9df58-1367-4abc-96df-9ba685522f95">

### To Reproduce

Open JSON

### Expected behavior

Open JSON

### Version information

-

**Comment by aurora-care-bear** [comment]
Thanks for submitting a issue!
to assign this issue to yourself please comment `@aurora-care-bear please assign me`

**Comment by 0xWDG** [comment]
Deprectated, this code is replaced.
