### ISSUE TITLE
Aurora Editor(94101,0x16d62b000) malloc: double free for ptr 0x15a98e000

### ISSUE THREAD

**Issue by 0xWDG** [AuroraEditor/AuroraEditor#666]
### Description

Aurora Editor(94101,0x16d62b000) malloc: double free for ptr 0x15a98e000

<img width="1532" alt="image" src="https://github.com/AuroraEditor/AuroraEditor/assets/1290461/3c3fb519-32d9-4979-8e72-2197f0f1768f">

### To Reproduce

-

### Expected behavior

-

### Version information

-

### Additional context

-

**Comment by aurora-care-bear** [comment]
Thanks for submitting a issue!
to assign this issue to yourself please comment `@aurora-care-bear please assign me`

**Comment by 0xWDG** [comment]
Deprectated, this code is replaced.
