### ISSUE TITLE
beginTasksIfNeeded EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by 0xWDG** [AuroraEditor/AuroraEditor#667]
### Description

beginTasksIfNeeded EXC_BAD_ACCESS

<img width="1532" alt="image" src="https://github.com/AuroraEditor/AuroraEditor/assets/1290461/e9cac9c2-70ef-4636-ab91-dd83f7e5d834">

### To Reproduce

https://github.com/appsterdam/api

Then `events.min.json`

### Expected behavior

No crash

### Version information

NA

**Comment by aurora-care-bear** [comment]
Thanks for submitting a issue!
to assign this issue to yourself please comment `@aurora-care-bear please assign me`

**Comment by 0xWDG** [comment]
Deprectated, this code is replaced.
