### ISSUE TITLE
Source Control: Uncaught Exception being thrown

### ISSUE THREAD

**Issue by nanashili** [AuroraEditor/AuroraEditor#668]
### Description

Sometimes an unknown exception is being thrown in the GitShell class:

```
Thread 1: signal SIGABRT
An abort signal terminated the process. Such crashes often happen because of an uncaught exception or unrecoverable error or calling the abort() function.
```

### To Reproduce

Open any Source Control functionality

### Expected behavior

Not to crash

### Version information

Aurora Editor: 0.1
Commit: [e.g. d06fb30e72634048395b5dbcdbc756b7f8ecc2f0]
MacOS: 15 beta
Xcode: 16 beta

**Comment by aurora-care-bear** [comment]
Thanks for submitting a issue!
to assign this issue to yourself please comment `@aurora-care-bear please assign me`
