### ISSUE TITLE
Changes in file system sometimes do not show up in the project navigator

### ISSUE THREAD

**Issue by KaiTheRedNinja** [AuroraEditor/AuroraEditor#69]
This bug seems to have been introduced in #67 workspace client rearchitecture. When a file is deleted/created, sometimes the sidebar isn't updated, however the WorkspaceClient seems to have the file indexed. Deleting/creating another file usually updates the sidebar so that both changes are shown, including the one previously not shown.

**Comment by 0xWDG** [comment]
PSA: I never encountered this issue.

**Comment by 0xWDG** [comment]
@KaiTheRedNinja does this still happen?

**Comment by KaiTheRedNinja** [comment]
I doubt so, but angelk said a while back that opening a project from the menu bar item causes the project navigator to be empty. I’ll check when I get home.
