### ISSUE TITLE
AE focus on itself after clicking on GitHub user profile popup and put AE to the background.

### ISSUE THREAD

**Issue by 0xWDG** [AuroraEditor/AuroraEditor#720]
### Description

AE focus on itself after clicking on GitHub user profile popup and put AE to the background.

https://github.com/user-attachments/assets/1b5fbfae-c6a4-4f14-98c6-b9fbf33a2802

### To Reproduce

Click a user.

### Expected behavior

Popup once.

### Version information

.

**Comment by aurora-care-bear** [comment]
Thanks for submitting a issue!
to assign this issue to yourself please comment `@aurora-care-bear please assign me`

**Comment by nanashili** [comment]
The better question is what's up with the spacing in the popover

**Comment by 0xWDG** [comment]
> The better question is what's up with the spacing in the popover

Small screen issues?

**Comment by 0xWDG** [comment]
Seems fixed in #725
