### ISSUE TITLE
Fatal error: Failed to generate EmptyURL

### ISSUE THREAD

**Issue by 0xWDG** [AuroraEditor/AuroraEditor#727]
### Description

AuroraEditor/emptyURL.swift:24: Fatal error: Failed to generate EmptyURL

<img width="1549" alt="image" src="https://github.com/user-attachments/assets/b42ff950-76fe-4f93-920e-cf2eaa2acfd2">

### To Reproduce

Close the editor

### Expected behavior

Not crash

### Version information

.

**Comment by aurora-care-bear** [comment]
Thanks for submitting a issue!
to assign this issue to yourself please comment `@aurora-care-bear please assign me`
