### ISSUE TITLE
Crash opening directory with recursive symlink

### ISSUE THREAD

**Issue by humblehacker** [AuroraEditor/AuroraEditor#739]
### Description

App hangs, then crashes when opening a directory containing a recursive symlink.

### To Reproduce

1. `mkdir testing`
2. `cd testing`
3. `ln -s .. recurse`
4. Open Aurora
5. Open directory `testing`

### Expected behavior

Directory opens

### Version information

Aurora Editor: 1.0 (1)
Commit: 752e6797c406c350d6bcd43c584ca13b446562c2
MacOS: 15.0 (24A5289h)
Xcode: 16.0 (16A5202i)

### Additional context

Originally found when opening https://github.com/groue/GRDB.swift

**Comment by aurora-care-bear** [comment]
Thanks for submitting a issue!
to assign this issue to yourself please comment `@aurora-care-bear please assign me`

**Comment by 0xWDG** [comment]
Closed in https://github.com/AuroraEditor/AuroraEditor/commit/0371bfd0f47212c92b3226aa4aedd4e49bc45af5

**Comment by 0xWDG** [comment]
Thanks 🩵
