### ISSUE TITLE
Depricate: Aurora Style Tabs

### ISSUE THREAD

**Issue by 0xWDG** [AuroraEditor/AuroraEditor#749]
### Is your feature request related to a problem? Please describe.

Change

### Describe the solution you'd like

Deprecatie: Aurora Style Tabbar/Tabs

### Describe alternatives you've considered

None.

### Additional context

To make the tabbar code less complex.
If we try to debug the code now, the compiler is complaining about not being able to type check within a reasonable time.

**Comment by aurora-care-bear** [comment]
Thanks for submitting a issue!
to assign this issue to yourself please comment `@aurora-care-bear please assign me`
