### ISSUE TITLE
Remove grey background from tabbar

### ISSUE THREAD

**Issue by 0xWDG** [AuroraEditor/AuroraEditor#755]
### Description

<img width="1057" alt="image" src="https://github.com/user-attachments/assets/fa0c1fca-bb4d-4fdc-9902-2aaf3fb83f98">

### To Reproduce

Merge https://github.com/AuroraEditor/AuroraEditor/pull/754

### Expected behavior

White/Clear background

### Version information

/

**Comment by aurora-care-bear** [comment]
Thanks for submitting a issue!
to assign this issue to yourself please comment `@aurora-care-bear please assign me`
