### ISSUE TITLE
When clicking around in the text view (Fatal error: Index out of range)

### ISSUE THREAD

**Issue by 0xWDG** [AuroraEditor/AuroraEditor#756]
### Description

When clicking around in the text view (Fatal error: Index out of range)

<img width="994" alt="image" src="https://github.com/user-attachments/assets/7538fffd-52f7-4e31-8b24-ec8402c3ea67">

### To Reproduce

Randomly happens sometimes

### Expected behavior

No crash

### Version information

x

### Additional context

Easy fix

**Comment by aurora-care-bear** [comment]
Thanks for submitting a issue!
to assign this issue to yourself please comment `@aurora-care-bear please assign me`

**Comment by 0xWDG** [comment]
@aurora-care-bear please verify
