### ISSUE TITLE
Tabs are broken on macOS 15+

### ISSUE THREAD

**Issue by 0xWDG** [AuroraEditor/AuroraEditor#776]
### Description

<img width="1356" alt="image" src="https://github.com/user-attachments/assets/cd5f50ff-3157-46cc-99c3-53ae57a81b30">

### To Reproduce

Open anything

### Expected behavior

Open file

### Version information

Aurora Editor: 1.0 (1)
Commit: 38f2847c0d7eadf6278d5a18149a9b00f0df272c
MacOS: 15.1 (24B83)
Xcode: 16.1 (16B40)

**Comment by aurora-care-bear** [comment]
Thanks for submitting a issue!
to assign this issue to yourself please comment `@aurora-care-bear please assign me`
