### ISSUE TITLE
The x button on the welcome screen is disappearing too quickly, on macOS 15+ it's almost impossible to close.

### ISSUE THREAD

**Issue by 0xWDG** [AuroraEditor/AuroraEditor#777]
### Description

The x button on the welcome screen is disappearing too quickly, on macOS 15+ it's almost impossible to close.

<img width="908" alt="image" src="https://github.com/user-attachments/assets/b12871bf-5738-4f4c-a857-e35747591e97">

### To Reproduce

Open welcome window

### Expected behavior

Able to close without issues

### Version information

Aurora Editor: 1.0 (1)
Commit: 38f2847c0d7eadf6278d5a18149a9b00f0df272c
MacOS: 15.1 (24B83)
Xcode: 16.1 (16B40)

**Comment by aurora-care-bear** [comment]
Thanks for submitting a issue!
to assign this issue to yourself please comment `@aurora-care-bear please assign me`
