### ISSUE TITLE
Package.resolved: No such file or directory

### ISSUE THREAD

**Issue by wdg** [AuroraEditor/AuroraEditor#78]
### Description

`Showing All Messages
/Users/nameUser/Desktop/AuroraEditor/Package.resolved: No such file or directory`.

### To Reproduce

^

### Expected behavior

*

### Version information

/

**Comment by nanashili** [comment]
Should be fixed in https://github.com/AuroraEditor/AuroraEditor/commit/ae7a573b487ca99ad4461906eaff9fc657c6c33c
